create table if not exists signup (
    user_id bigint generated by default as identity primary key,
    useremail varchar(100) unique not null check (useremail like '%@%'),
    userfirstname varchar(50) not null,
    userlastname varchar(50) not null,
    passwordhash text not null check (length(passwordhash) >= 8),
    reward_points integer default 0 check (reward_points >= 0),
    created_at timestamp default now()
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    userid bigint references signup(user_id),
    total numeric(10,2) not null check (total >= 0),
    reward_points_earned integer default 0 check (reward_points_earned >= 0),
    created_at timestamp default now()
);