--- Adding the schema for my Supabase database

--- Code to create table
CREATE TABLE Tbl_customer_appointments (
  appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name TEXT NOT NULL,
  patient_dob DATE NOT NULL,
  patient_telephone TEXT NOT NULL,
  patient_address TEXT NOT NULL,
  patient_medical_history TEXT NOT NULL,
  patient_next_of_kin TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

--- Code to insert into table
INSERT INTO Tbl_customer_appointments(
    patient_name,
    patient_dob,
    patient_telephone,
    patient_address,
    patient_medical_history,
    patient_next_of_kin
) VALUES
('Alice Johnson', '1985-03-14', '+447912345678', '12 High Street, Shrewsbury, SY1 1AA', 'Asthma, mild', 'Robert Johnson'),
('James Smith', '1990-07-22', '07987654321', '45 Market Road, Birmingham, B1 2AB', 'No known allergies', 'Sarah Smith'),
('Emily Brown', '1978-11-05', '+447700900123', '89 Church Lane, Manchester, M3 4FG', 'Type 2 Diabetes', 'Michael Brown'),
('Oliver Davis', '2000-02-18', '07700900111', '23 Park Avenue, London, SW1A 1AA', 'Seasonal hay fever', 'Laura Davis'),
('Sophie Wilson', '1969-09-30', '+447911223344', '67 Green Street, Leeds, LS2 7PT', 'Hypertension', 'David Wilson'),
('George Taylor', '1982-06-12', '07812345678', '14 King Street, Liverpool, L1 8JQ', 'Migraines', 'Emma Taylor'),
('Charlotte Evans', '1995-12-01', '+447845678901', '88 Queen Road, Bristol, BS1 4ST', 'Eczema', 'Daniel Evans'),
('Henry Walker', '1975-04-23', '07700900456', '32 Victoria Avenue, Newcastle, NE1 3DX', 'High cholesterol', 'Anna Walker'),
('Amelia Harris', '1988-08-19', '+447700900789', '56 Bridge Street, Cardiff, CF10 1AA', 'Asthma', 'Thomas Harris'),
('Jacob Lewis', '1993-11-11', '07900112233', '101 Oxford Street, London, W1D 2LT', 'No known allergies', 'Grace Wallis');

--- Enabling security
ALTER TABLE tbl_customer_appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow insert to anon"
ON tbl_customer_appointments
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow select to anon"
ON tbl_customer_appointments
FOR SELECT
TO anon
USING (true);

--- Allow anon insertions
DROP POLICY IF EXISTS "Allow insert to anon" ON tbl_customer_appointments;
DROP POLICY IF EXISTS "Allow select to anon" ON tbl_customer_appointments;

CREATE POLICY "Allow insert to anon"
ON tbl_customer_appointments FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow select to anon"
ON tbl_customer_appointments FOR SELECT TO anon USING (true);

